# Milvus默认参数
Milvus:
  default_index_type: FLAT
  index_params:
    FLAT:
    IVF_FLAT:
      nlist: 1024
      nprobe: 16
    HNSW:
      efConstruction: 100
  default_metric_type: L2

# LanceDB默认参数
LanceDB:
  default_index_type: IVF_PQ
  default_metric_type: L2

# 嵌入模型参数
embedding_model:
  bge-small-zh-v1.5:
    path: models/embedding/bge-small-zh-v1.5
    dim: 512
  stella-base-zh-v2:
    path: models/embedding/stella-base-zh-v2
    dim: 768

# Redis
Redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
